### ISSUE TITLE
Issue with npm instructions in README.md

### ISSUE THREAD

**Issue by mattlaver** [karma-runner/karma-script-launcher#1]
I think there is a typo in the instructions on how to install here:

npm install karma-scripts-launcher --save-dev

I found I had to drop the s:

npm install karma-script-launcher --save-dev

**Comment by hashchange** [comment]
Indeed. And yes, it is not a big deal. But it sends any new user to a Google round trip, and correcting the typo takes about as long as me typing this message. Perhaps worth a "fix" after n>1 years? Thanks!

**Comment by jondeodat** [comment]
Yes the readme is not accurate, it is written scripts everywhere instead of script. Plus the npmjs page is also not accurate. There is the same typo everywhere. It is also mentionned to not install it because it should be already in karma which is false too. https://www.npmjs.com/package/karma-script-launcher

**Comment by joeyparrish** [comment]
This was fixed by ac3493a7 and #2.  Can someone please close this issue and make a new release on npm?  The last release still has the broken instructions.

**Comment by dignifiedquire** [comment]
Done
